version: '3.9'

services:
  fireplace-api:
    image: fireplaceapi/fireplace-api
    container_name: fireplace-api
    ports:
      - '3301:5000'
    volumes:
      - ./logs:/logs
      - /bitiano/files/files.fireplace.bitiano.com:/files
    environment:
      - FIREPLACE_API_ASPNETCORE_ENVIRONMENT=Production
      - FIREPLACE_API_LOG_DIRECTORY=/logs
      - FIREPLACE_API_CONNECTION_STRING
    networks:
      - fireplace-api-network

networks:
  fireplace-api-network:
    name: fireplace-api-network
