name: CICD

on: workflow_dispatch
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  ASPNETCORE_ENVIRONMENT: Production
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --logger "console;verbosity=detailed"

    - name: Publish
      run: dotnet publish -c Release -o app

    - name: Upload publish files
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: |
          app
          Dockerfile
          docker-compose.yml
  
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
    - name: Download publish files
      uses: actions/download-artifact@v3
      with:
        name: publish

    - name: Check files
      run: |
        echo "root:"
        ls -alh
        echo "\n\napp:"
        ls -alh app
