name: CICD

on: workflow_dispatch
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  ASPNETCORE_ENVIRONMENT: Production
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "console;verbosity=detailed"
    - name: Cache app
      id: app-cache
      uses: actions/cache@v3
      with:
        path: app
        key: app-cache
    - name: Publish
      run: dotnet publish -c Release -o app
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Using app cache
      id: app-cache
      uses: actions/cache@v3
      with:
        path: app
        key: app-cache
    - name: Check app directory
      run: ls -alh app
